name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: for proj in `find . -name *.Tests.csproj`; do dotnet test $proj --no-restore --no-build; done
    - name: Pack
      run: dotnet pack --no-restore --no-build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: nupkgs
        path: _artifacts/**/*
