name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Restore dependencies
      run: dotnet restore /v:n /bl:_artifacts/restore.binlog
    - name: Upload restore.binlog
      uses: actions/upload-artifact@v2.2.4
      with:
        path: _artifacts/restore.binlog

    - name: Build
      run: dotnet build --no-restore /v:n /bl:_artifacts/build.binlog
    - name: Upload build.binlog
      uses: actions/upload-artifact@v2.2.4
      with:
        path: _artifacts/build.binlog

    - name: Test
      run: for proj in `find . -name *.Tests.csproj`; do dotnet test $proj --no-restore --no-build; done

    - name: Pack
      run: dotnet pack --no-restore --no-build /v:n /bl:_artifacts/pack.binlog
    - name: Upload pack.binlog
      uses: actions/upload-artifact@v2.2.4
      with:
        path: _artifacts/pack.binlog

    - name: Upload Packages
      uses: actions/upload-artifact@v2.2.4
      with:
        name: nupkgs
        path: _artifacts/**/*.nupkg
